### PR TITLE
Added PHP South West to the page :) 

### PR DESCRIPTION
**Pull request by katzien**
We'd be more than happy to include a link back to PHP Women in our "Friends" section in return!

### CODE REVIEW

**Comment by katzien** [comment]
Could I please get an update on this? :)

**Comment by katzien** [comment]
Thank you Michelle! :)

**Comment by michellesanver** [comment]
No problem! Sorry it took so long, totally missed it in my notifications!

**Comment by katzien** [comment]
Hey Michelle!

Sorry to be bugging you again... I still can't see PHPSW on your website? Just wondering if I did something wrong, or did you not deploy the new version of the website yet?

Thanks for your help!
Kat

**Pull request merged**
